name: Create Apple Distribution P12

on:
  workflow_dispatch:

jobs:
  create-p12:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create P12
        env:
          CERT_KEY_PASSWORD: ${{ secrets.CERT_KEY_PASSWORD }}
        run: |
          openssl pkcs12 -export \
            -inkey distribution.key \
            -passin env:CERT_KEY_PASSWORD \
            -in "distribution 2.cer" \
            -out distribution.p12 \
            -passout env:CERT_KEY_PASSWORD

      - name: Upload P12
        uses: actions/upload-artifact@v4
        with:
          name: PetKarnem-Distribution-P12
          path: distribution.p12
